### ISSUE TITLE
Can't authenticate using gitlab feature flags integration

### ISSUE THREAD

**Issue by okesland** [Unleash/unleash-android#76]
### Describe the bug

I'm integrating unleash android into my app and I'm not able to get correctly authenticated.

Here's a basic client configuration.

```
@Provides
fun provideUnleashClient(
    @ApplicationContext applicationContext: Context,
): DefaultUnleash = DefaultUnleash(
    androidContext = applicationContext,
    unleashConfig =  UnleashConfig.newBuilder(appName = "test-app-name")
        .proxyUrl("https://gitlab.com/api/v4/feature_flags/unleash/60447338")
        .clientKey("glffct-tAf...")
        .build()
)
```

I'm able to make a regular http call using gitlab api with a slightly modified URL `https://gitlab.com/api/v4/projects/60447338/feature_flags` and a newly generated access token.
But even feeding this into android SDK returns 401.

### Steps to reproduce the bug

To reproduce you can follow this docs to [get access credentials](https://docs.gitlab.com/ee/operations/feature_flags.html#get-access-credentials)
To get the access credentials that your application needs to communicate with GitLab:

1. On the left sidebar, select Search or go to and find your project.
2. Select Deploy > Feature flags.
3. Select Configure to view the following:
- API URL: URL where the client (application) connects to get a list of feature flags.
- Instance ID: Unique token that authorizes the retrieval of the feature flags.
- Application name: The name of the environment the application runs in (not the name of the application itself).

### Expected behavior

When the access credentials from Gitlab are used for unleash-android SDK it is possible to connect and fetch feature flags.

### Logs, error output, etc.

```bash
16:33:21.591 Unleash                  D  Using lifecycle from ProcessLifecycleOwner
16:33:21.659 UnleashFetcher           D  Refreshing toggles
16:33:21.662 UnleashFetcher           D  Fetching toggles from https://gitlab.com/api/v4/feature_flags/unleash/60447338?appName=test-app-name
16:33:22.045 UnleashFetcher           D  Received status code 401 from https://gitlab.com/api/v4/feature_flags/unleash/60447338?appName=test-app-name
16:33:22.045 Throttler                E  Client was not authorized to talk to the Unleash API at https://gitlab.com/api/v4/feature_flags/unleash/60447338. Backing off to 5 times our poll interval (of 60 seconds) to avoid overloading server
16:33:22.047 UnleashFetcher           E  Not authorized to fetch toggles. Double check your SDK key
16:33:22.062 Unleash                  D  Loading state from backup for UnleashContext(userId=null, sessionId=null, remoteAddress=null, properties={})
16:33:22.063 UnleashFetcher           D  Unleash context changed: UnleashContext(userId=null, sessionId=null, remoteAddress=null, properties={})
16:33:22.063 UnleashFetcher           I  Skipping refresh toggles due to throttling
```

### Screenshots

<img width="767" alt="Screenshot 2024-07-30 at 16 29 04" src="https://github.com/user-attachments/assets/acbbb50e-fbf1-4441-b56a-3908b1c0249a">

### Additional context

I'm on selfhosted Gitlab, but also with the general one the problem is the same.

I've checked a sample Ruby script from gitlab docs  and it works perfectly fine with the same Gitlab credentials

### Unleash version

1.0.1

### Subscription type

None

### Hosting type

Self-hosted

**Comment by gastonfournier** [comment]
Hi @okesland I'll try to reproduce this (thanks for the steps to reproduce!). I just wanted to clarify some details:
- https://gitlab.com/api/v4/feature_flags/unleash/60447338 is the URL that Gitlab recommends you to use, right?
- https://gitlab.com/api/v4/projects/60447338/feature_flags is the URL that you managed to use with Gitlab but doesn't work with the SDK, right?
- How did you come up with that url? I'm just suspecting that Gitlab needs to update their documentation, but even if that's the case the url should work with the SDK.
- Out of curiosity, were you using the previous version of the Android SDK? If yes, was it working?

I'll do some testing of my own, but maybe you already have answers for those questions.

**Comment by okesland** [comment]
@gastonfournier 
- yes, https://gitlab.com/api/v4/feature_flags/unleash/60447338 is a URL which is provided by Gitlab. It's displayed in an attached screenshot during config
- yes, this URL https://gitlab.com/api/v4/projects/60447338/feature_flags is an endpoint to fetch feature flags of a project. It works with a [personal](https://docs.gitlab.com/ee/user/profile/personal_access_tokens.html) or [project](https://docs.gitlab.com/ee/user/project/settings/project_access_tokens.html) access token (or opening in a browser when you're logged in). Using this URL in unleash SDK actually returns 404 instead of 401 error.
- The API for Gitlab feature flags is documented [here](https://docs.gitlab.com/ee/api/feature_flags.html). So that's where I've got the working API URL.
- I tried to use a sample app from the old SDK https://github.com/Unleash/unleash-android-proxy-sdk/tree/main/samples/android
I used these Gitlab access credentials, but there's nothing in logs. I'm not even sure if it's running or not. In the new SDK there's a method `start()`. When I call it my auth starts and fails as described above. But with the old SDK sample app there's nothing as such. Even when calling `unleashClient.startPolling()` nothing happens. Even with the default URL and key. So hard to tell if it works at all.
And `unleashClient.isEnabled("test-flag")` always returns false (even though I created and enabled `test-flag` in the system).

I roughly looked through the code of both SDKs and one difference I can see during request is that the old one has only one header `"Authorization"`. Whereas the new one has a few more:
```
        return strategy.httpCustomHeaders.plus(mapOf(
            "Authorization" to auth,
            "Content-Type" to "application/json",
            "UNLEASH-APPNAME" to appName,
            "User-Agent" to appName,
            "UNLEASH-INSTANCEID" to instanceId,
        ))
```
I doubt it's very relevant, but I couldn't find anything better.

**Comment by gastonfournier** [comment]
Hi! Thanks so much about these details. I was puzzled with the fact that Gitlab uses the instanceId for authentication while we don't use it for that purpose (that's why the Android SDK does not allow you to set the instanceId property). 

After checking with my teammates we realized that in fact the problem is that the Android SDK needs to connect to a [proxy-API](https://docs.getunleash.io/reference/unleash-proxy#api) as defined by Unleash. But Gitlab API does not provide such API.

The trick is that you need to add an adapter component. In particular you need to run a proxy as explained here: https://docs.gitlab.com/ee/operations/feature_flags.html#unleash-proxy-example

Following your example you should do something like:
```shell
docker run -e UNLEASH_PROXY_SECRETS=1234567 \                                                                                                                                                             
  -e UNLEASH_URL=https://gitlab.com/api/v4/feature_flags/unleash/60447338 \
  -e UNLEASH_INSTANCE_ID=glffct-tAf... \
  -e UNLEASH_APP_NAME=development \
  -e UNLEASH_API_TOKEN=tokenNotUsed \
  -p 3000:3000 \
  unleashorg/unleash-proxy
```

Then I used ngrok to expose the port of proxy on my localhost (`ngrok http 3000`)

and my configuration became:
```kotlin
    unleashConfig =  UnleashConfig.newBuilder(appName = "test-app-name")
        .proxyUrl("https://dc3e-2a03-4460-121e-cf00-7863-59ac-d5d7-6601.ngrok-free.app/proxy")
        .clientKey("1234567") // same one defined in the proxy as UNLEASH_PROXY_SECRETS
        .build()
```

With that configuration the sample app worked well for me. Note that the environment variable is defined at the proxy configuration as APP_NAME

Please, let me know if we can close the issue

**Comment by okesland** [comment]
Thank you for this very detailed explanation. Now I understand the problem.
I wasn't aware that unleash proxy is necessary here. Based on Gitlab documentation I thought it's optional. Now I can see that in your README proxy is mentioned multiple times.

Now I know what I need for my setup to work.

In this case I we can close the issue.

**Comment by gastonfournier** [comment]
Thanks! And because you're the first known user of this new version of the Android SDK, please let us know if you have any feedback either in Github or our community Slack: https://slack.unleash.run/
