### ISSUE TITLE
Add ability to pass own OkHttpClient to DefaultUnleash

### ISSUE THREAD

**Issue by vassilisimon** [Unleash/unleash-android#84]
### Describe the feature request

Hello,

in the old unleash-proxy-sdk it was possible to pass a OkHttpClient to the UnleashClient.
This isn't possible anymore with the new sdk. It would be nice to have this ability again, as we need it so support devices with api < 23 with custom certificates.

**Comment by chriswk** [comment]
Hi @vassilisimon. Thanks for reporting this, we've added it to our todo list

**Comment by chriswk** [comment]
@gastonfournier - let's have a spar on this
