### ISSUE TITLE
refreshToggles() is not called after setContextAsync()

### ISSUE THREAD

**Issue by ericxiewen** [Unleash/unleash-android#96]
### Describe the bug

fun startWatchingContext() {
        unleashScope.launch {
            unleashContext.distinctUntilChanged { old, new -> old != new }.collect {
                withContext(coroutineContextForContextChange) {
                    Log.d(TAG, "Unleash context changed: $it")
                    refreshToggles()
                }
            }
        }
    }
    
The conditional judgment of "unleashContext.distinctUntilChanged" is written in reverse, should be:
unleashContext.distinctUntilChanged { old, new -> old == new }

See Kotlin document:
/**
 * Returns flow where all subsequent repetitions of the same value are filtered out, when compared
 * with each other via the provided [areEquivalent] function.
 *
 * Note that repeated application of `distinctUntilChanged` operator with the same parameter has no effect.
 */
@Suppress("UNCHECKED_CAST")
public fun <T> Flow<T>.distinctUntilChanged(areEquivalent: (old: T, new: T) -> Boolean): Flow<T>

### Subscription type

None

### Hosting type

None

**Comment by chriswk** [comment]
Hi @ericxiewen - thanks for reporting this. Sorry for the trouble, I've started on the suggested patch. 

Will get a co-worker to review before releasing a patch version.

**Comment by chriswk** [comment]
I see my co-worker is OOO today and Monday. So this will happen on Tuesday. Sorry

**Comment by ericxiewen** [comment]
Thanks for your quick fix!
